version: '3'
services:
  mysql:
    image: "mysql"
    networks:
      - main
    ports:
     - "3306:3306"
    environment:
     - MYSQL_DATABASE=askgames
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=local
     - MYSQL_PASSWORD=1234
    volumes:
      - lph-mysql:/var/lib/mysql
networks:
  main:
volumes:
  lph-mysql:
    external: true
