version: '3'
services:
  mysql:
    restart: always
    image: "mysql"
    networks:
      - main
    ports:
     - "3306:3306"
    environment:
     - MYSQL_DATABASE=askgames
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=local
     - MYSQL_PASSWORD=1234
    volumes:
      - lph-mysql:/var/lib/mysql
  redis:
    restart: always
    image: "redis"
    networks:
      - main
    ports:
      - "6379:6379"
    volumes:
      - lph-redis:/data
  store-node:
    image: dhub.nvx.me:443/ag-store-node
    networks:
      - main
    ports:
      - "4080:80"
    volumes:
      - ./store:/var/store
networks:
  main:
volumes:
  lph-mysql:
    external: true
  lph-redis:
      external: true
